### ISSUE TITLE
Traceback (most recent call last):   File "hackinsta.py", line 154, in <module>     sess = instabrute.Login(password)   File "hackinsta.py", line 118, in Login     sess.headers.update({'X-CSRFToken' : r.cookies.get_dict()['csrftoken']}) KeyError: 'csrftoken'

### ISSUE THREAD

**Issue by vrushal11** [Sanif007/instahack#5]

**Comment by elio-bteich** [comment]
i have the same issue

**Comment by Adarsh001-hacker** [comment]
Same issue here
